name: Homfen's Blog
description: My New Jekyll Site,That's It.
meta_description: ""

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /jekyll/
domain_name: 'http://homfen.github.io'

# Details for the RSS feed generator
url:            'http://homfen.github.io/jekyll/'
author:         'Homfen'
